Repository alexgo-io/alex-v1, pull requests merged in 2021-09, with the labels that each got.

#117 fix: #116
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/pool/liquidity-bootstrapping-pool.clar
Labels: bug

#134 merge fix/133 into feature/124
  clarity/contracts/pool/collateral-rebalancing-pool.clar
Labels: bug, dev, collateral-rebalancing-pool

#145 Feature/main/sidney
  clarity/Clarinet.toml
  clarity/contracts/collateral-rebalancing-pool.clar
  clarity/contracts/fixed-weight-pool.clar
  clarity/contracts/flash-loan-user-margin.clar
  clarity/contracts/key-usda-wbtc-59760.clar
  clarity/contracts/liquidity-bootstrapping-pool.clar
  clarity/contracts/yield-token-pool.clar
  clarity/contracts/yield-usda-59760.clar
  clarity/deploy-util/.DS_Store
  clarity/deploy-util/deployed-contracts.json
  clarity/deploy-util/scripts/deploy.py
  clarity/tests/collateral-rebalancing-pool_test.ts
  clarity/tests/liquidity-bootstrapping-pool_test.ts
  scripts/batches/8/key-usda-wbtc-59760.clar
  scripts/batches/8/yield-usda-59760.clar
  scripts/deploy_keychain.json
Labels: dev, regtest-v1

#127 merge #105 to dev
  clarity/Clarinet.toml
  clarity/contracts/alex-vault.clar
  clarity/contracts/flash-loan-user-margin-usda-wbtc-4380.clar
  clarity/contracts/flash-loan-user-test.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/contracts/test-flash-loan-user.clar
  clarity/contracts/traits/trait-vault.clar
  clarity/tests/flash-loan-user-margin_test.ts
  clarity/tests/flash-loan_test.ts
  diagrams/.DS_Store
  diagrams/use-case-borrower-repay.png
  diagrams/use-case-borrower.png
  diagrams/use-case-flashloan.yuml
  diagrams/use-case-lender-expiry.png
  diagrams/use-case-lender-expiry.svg
  diagrams/use-case-margin.png
Labels: dev, vault

#128 merge #123 into dev
  clarity/Clarinet.toml
  clarity/contracts/key-token/key-usda-wbtc-4380.clar
  clarity/contracts/multisig/alex-crp-wbtc-usda-4380-multisig.clar
  clarity/contracts/multisig/alex-ytp-wbtc-usda-4380-multisig.clar
  clarity/contracts/open-oracle.clar
  clarity/contracts/pool-token/pool-token-alex-usda.clar
  clarity/contracts/pool-token/pool-token-usda-ayusda.clar
  clarity/contracts/pool-token/pool-token-yield-usda-wbtc.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/pool/liquidity-bootstrapping-pool.clar
  clarity/contracts/pool/yield-token-pool.clar
  clarity/contracts/token/token-alex.clar
  clarity/contracts/token/token-usda.clar
  clarity/contracts/token/token-wbtc.clar
  clarity/contracts/traits/trait-alex-token.clar
  clarity/contracts/yield-token/yield-usda-18530.clar
  clarity/contracts/yield-token/yield-usda-4380.clar
  clarity/tests/fixed-weight-pool_test.ts
  clarity/tests/models/alex-tests-collateral-rebalancing-pool.ts
  clarity/tests/models/alex-tests-fixed-weight-pool.ts
  clarity/tests/models/alex-tests-liquidity-bootstrapping-pool.ts
  clarity/tests/models/alex-tests-yield-token-pool.ts
  clarity/tests/yield-token-pool_test.ts
  clarity/wip/alex-multisig-registry/alex-multisig-registry.clar
  clarity/wip/alex-multisig-registry/alex-multisig-registry.toml
Labels: bug, dev

#125 merge #124 into dev
  clarity/Clarinet.toml
  clarity/contracts/alex-reserve-pool.clar
  clarity/contracts/pool-token/pool-token-alex-usda.clar
  clarity/contracts/pool-token/pool-token-usda-ayusda.clar
  clarity/contracts/pool-token/pool-token-yield-usda-wbtc.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/pool/liquidity-bootstrapping-pool.clar
  clarity/contracts/pool/yield-token-pool.clar
  clarity/contracts/token/token-alex.clar
  clarity/contracts/token/token-usda.clar
  clarity/contracts/token/token-wbtc.clar
  clarity/contracts/traits/trait-pool-token.clar
  clarity/tests/alex-reserve-pool_test.ts
Labels: dev

#152 merge `fix/151` into `dev`
  clarity/contracts/pool/collateral-rebalancing-pool.clar
Labels: bug, dev, collateral-rebalancing-pool

#162 fix: #161
  clarity/contracts/pool/yield-token-pool.clar
Labels: bug, dev, yield-token-pool

#165 merge hotfix/163 into main
  clarity/.DS_Store
  clarity/Clarinet.toml
  clarity/contracts/alex-multisig-registry.clar
  clarity/contracts/alex-ytp-multisig-vote.clar
  clarity/contracts/collateral-rebalancing-pool.clar
  clarity/contracts/fixed-weight-pool.clar
  clarity/contracts/flash-loan-user-margin.clar
  clarity/contracts/key-usda-wbtc-4380.clar
  clarity/contracts/key-usda-wbtc-59760.clar
  clarity/contracts/liquidity-bootstrapping-pool.clar
  clarity/contracts/math-fixed-point.clar
  clarity/contracts/math-log-exp.clar
  clarity/contracts/multisig-yield-usda-4380-wbtc.clar
  clarity/contracts/pool-token-alex-usda.clar
  clarity/contracts/pool-token-yield-usda-4380-usda.clar
  clarity/contracts/pool-token-yield-usda-4380-wbtc.clar
  clarity/contracts/pool-token-yield-usda-59760-usda.clar
  clarity/contracts/pool-token-yield-usda-59760-wbtc.clar
  clarity/contracts/test-flash-loan-user.clar
  clarity/contracts/token-alex.clar
  clarity/contracts/token-usda.clar
  clarity/contracts/token-wbtc.clar
  clarity/contracts/trait-alex-token.clar
  clarity/contracts/trait-flash-loan-user.clar
  clarity/contracts/trait-multisig-vote.clar
  clarity/contracts/trait-oracle.clar
  clarity/contracts/trait-pool-token.clar
  clarity/contracts/trait-sip-010.clar
  clarity/contracts/trait-vault.clar
  clarity/contracts/trait-yield-token.clar
  clarity/contracts/weighted-equation.clar
  clarity/contracts/yield-token-equation.clar
  clarity/contracts/yield-token-pool.clar
  clarity/contracts/yield-usda-18530.clar
  clarity/contracts/yield-usda-4380.clar
  clarity/contracts/yield-usda-59760.clar
  clarity/deploy-util/batches/.DS_Store
  clarity/deploy-util/batches/3/token-alex.clar
  clarity/deploy-util/batches/3/token-usda.clar
  clarity/deploy-util/batches/3/token-wbtc.clar
  clarity/deploy-util/batches/4/key-usda-wbtc-4380.clar
  clarity/deploy-util/batches/4/key-usda-wbtc-59760.clar
  clarity/deploy-util/batches/4/pool-token-usda-59760-usda.clar
  clarity/deploy-util/batches/4/pool-token-usda-59760-wbtc.clar
  clarity/deploy-util/batches/4/yield-usda-18530.clar
  clarity/deploy-util/batches/4/yield-usda-4380.clar
  clarity/deploy-util/batches/4/yield-usda-59760.clar
  clarity/deploy-util/batches/5/open-oracle.clar
  clarity/deploy-util/batches/6/fixed-weight-pool.clar
  clarity/deploy-util/batches/7/collateral-rebalancing-pool.clar
  clarity/deploy-util/batches/7/liquidity-bootstrapping-pool.clar
  clarity/deploy-util/batches/7/yield-token-pool.clar
  clarity/tests/alex-vault_test.ts
  clarity/tests/collateral-rebalancing-pool_test.ts
  clarity/tests/fixed-weight-pool_test.ts
  clarity/tests/flash-loan_test.ts
  clarity/tests/liquidity-bootstrapping-pool_test.ts
  clarity/tests/weighted-equation_test.ts
  clarity/tests/yield-token-equation_test.ts
  clarity/tests/yield-token-pool_test.ts
Labels: bug, dev, regtest-v1

#171 math-fixed-point_test.ts added (#169)
  clarity/tests/alex-crp-multisig-vote_test.ts
  clarity/tests/alex-reserve-pool_test.ts
  clarity/tests/alex-vault_test.ts
  clarity/tests/collateral-rebalancing-pool_test.ts
  clarity/tests/fixed-weight-pool_test.ts
  clarity/tests/flash-loan-user-margin_test.ts
  clarity/tests/flash-loan_test.ts
  clarity/tests/liquidity-bootstrapping-pool_test.ts
  clarity/tests/math-fixed-point_test.ts
  clarity/tests/oracle-simulation-test.ts
  clarity/tests/weighted-equation_test.ts
  clarity/tests/yield-token-equation_test.ts
  clarity/tests/yield-token-pool_test.ts
Labels: dev, regtest-v1

#174 build test cases for yield-token-pool (#173)
  clarity/contracts/equations/yield-token-equation.clar
  clarity/contracts/multisig/multisig-ytp-yield-wbtc-59760-wbtc.clar
  clarity/contracts/pool-token/ytp-yield-wbtc-59760-wbtc.clar
  clarity/contracts/pool-token/ytp-yield-wbtc-79760-wbtc.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/pool/liquidity-bootstrapping-pool.clar
  clarity/contracts/pool/yield-token-pool.clar
  clarity/contracts/traits/trait-multisig-vote.clar
  clarity/contracts/yield-token/yield-wbtc-59760.clar
  clarity/out
  clarity/tests/models/alex-tests-yield-token-pool.ts
  clarity/tests/yield-token-pool_test.ts
Labels: dev, regtest-v1

#188 test cases for reserve pool / shortfall added (#187)
  clarity/contracts/equations/weighted-equation.clar
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/token/token-usda.clar
  clarity/tests/collateral-rebalancing-pool_test.ts
  clarity/tests/models/alex-tests-collateral-rebalancing-pool.ts
  clarity/tests/models/alex-tests-fixed-weight-pool.ts
  clarity/tests/models/alex-tests-oracle-mock.ts
  clarity/tests/models/alex-tests-yield-token-pool.ts
Labels: dev

#182 Fix/fwp/testcases #180, #181 - FWP part
  clarity/contracts/multisig/multisig-crp-wbtc-59760-usda.clar
  clarity/contracts/multisig/multisig-fwp-wbtc-usda-50-50.clar
  clarity/contracts/multisig/multisig-ytp-yield-wbtc-59760-wbtc.clar
  clarity/contracts/multisig/multisig-ytp-yield-wbtc-79760-wbtc.clar
  clarity/contracts/traits/trait-multisig-vote.clar
  clarity/tests/fixed-weight-pool_test.ts
  clarity/tests/history.txt
  clarity/tests/models/alex-tests-fixed-weight-pool.ts
  clarity/tests/models/alex-tests-multisigs.ts
  clarity/tests/models/alex-tests-tokens.ts
  clarity/tests/yield-token-pool_test.ts
Labels: dev

#193 test cases for margin trading
  clarity/Clarinet.toml
  clarity/contracts/alex-vault.clar
  clarity/contracts/flash-loan-user-margin-usda-wbtc-59760.clar
  clarity/contracts/flash-loan-user-margin-wbtc-usda-59760.clar
  clarity/contracts/pool/yield-token-pool.clar
  clarity/contracts/token/token-usda.clar
  clarity/tests/flash-loan_test.ts
  clarity/tests/models/alex-tests-flash-loan.ts
Labels: dev

#198 fixed #194 and added #197
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  init-js-tool/index.js
  init-js-tool/oracles.js
  init-js-tool/yarn.lock
Labels: bug, dev

#207 math lib moved to body of equations/pools (#206)
  clarity/contracts/equations/weighted-equation.clar
  clarity/contracts/equations/yield-token-equation.clar
  clarity/contracts/pool/alex-reserve-pool.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/pool/liquidity-bootstrapping-pool.clar
  clarity/contracts/pool/yield-token-pool.clar
Labels: dev

#215 added more functions to pools.js
  README.md
  init-js-tool/index.js
  init-js-tool/pools.js
Labels: dev

#219 fixed #218
  clarity/contracts/equations/weighted-equation.clar
  clarity/contracts/equations/yield-token-equation.clar
  clarity/contracts/pool/alex-reserve-pool.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/pool/liquidity-bootstrapping-pool.clar
  clarity/contracts/pool/yield-token-pool.clar
Labels: bug, dev

#217 add tx-sender guard
  clarity/Clarinet.toml
  clarity/contracts/alex-vault.clar
  clarity/contracts/equations/weighted-equation.clar
  clarity/contracts/flash-loan-user-margin-usda-wbtc-59760.clar
  clarity/contracts/key-token/key-wbtc-59760-usda.clar
  clarity/contracts/key-token/key-wbtc-79760-usda.clar
  clarity/contracts/open-oracle.clar
  clarity/contracts/pool-token/fwp-wbtc-usda-50-50.clar
  clarity/contracts/pool-token/ytp-yield-wbtc-59760-wbtc.clar
  clarity/contracts/pool-token/ytp-yield-wbtc-79760-wbtc.clar
  clarity/contracts/pool/alex-reserve-pool.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/pool/liquidity-bootstrapping-pool.clar
  clarity/contracts/pool/yield-token-pool.clar
  clarity/contracts/token/token-alex.clar
  clarity/contracts/token/token-usda.clar
  clarity/contracts/token/token-wbtc.clar
  clarity/contracts/traits/trait-ownable.clar
  clarity/contracts/yield-token/yield-wbtc-59760.clar
  clarity/contracts/yield-token/yield-wbtc-79760.clar
  clarity/tests/fixed-weight-pool_test.ts
  init-js-tool/index.js
  init-js-tool/pools.js
Labels: dev

#222 Node deploy scripts
  init-js-tool/batches/01/math-log-exp.clar
  init-js-tool/batches/02/math-fixed-point.clar
  init-js-tool/batches/03/trait-flash-loan-user.clar
  init-js-tool/batches/03/trait-oracle.clar
  init-js-tool/batches/03/trait-pool-token.clar
  init-js-tool/batches/03/trait-sip-010.clar
  init-js-tool/batches/03/trait-yield-token.clar
  init-js-tool/batches/03/weighted-equation.clar
  init-js-tool/batches/03/yield-token-equation.clar
  init-js-tool/batches/04/fwp-wbtc-usda-50-50.clar
  init-js-tool/batches/04/key-wbtc-59760-usda.clar
  init-js-tool/batches/04/key-wbtc-79760-usda.clar
  init-js-tool/batches/04/open-oracle.clar
  init-js-tool/batches/04/trait-multisig-vote.clar
  init-js-tool/batches/04/trait-vault.clar
  init-js-tool/batches/04/yield-wbtc-59760.clar
  init-js-tool/batches/04/yield-wbtc-79760.clar
  init-js-tool/batches/04/ytp-yield-wbtc-59760-wbtc.clar
  init-js-tool/batches/04/ytp-yield-wbtc-79760-wbtc.clar
  init-js-tool/batches/05/alex-vault.clar
  init-js-tool/batches/05/token-alex.clar
  init-js-tool/batches/05/token-usda.clar
  init-js-tool/batches/05/token-wbtc.clar
  init-js-tool/batches/06/alex-reserve-pool.clar
  init-js-tool/batches/07/fixed-weight-pool.clar
  init-js-tool/batches/08/liquidity-bootstrapping-pool.clar
  init-js-tool/batches/08/yield-token-pool.clar
  init-js-tool/batches/09/collateral-rebalancing-pool.clar
  init-js-tool/batches/09/flash-loan-user-margin-usda-wbtc-59760.clar
  init-js-tool/batches/10/multisig-crp-wbtc-59760-usda.clar
  init-js-tool/batches/10/multisig-crp-wbtc-79760-usda.clar
  init-js-tool/batches/10/multisig-fwp-wbtc-usda-50-50.clar
  init-js-tool/batches/10/multisig-ytp-yield-wbtc-59760-wbtc.clar
  init-js-tool/batches/10/multisig-ytp-yield-wbtc-79760-wbtc.clar
  init-js-tool/deploy.js
  init-js-tool/package-lock.json
  init-js-tool/package.json
Labels: dev

#223 merge dev into main
  clarity/Clarinet.toml
  clarity/contracts/alex-vault.clar
  clarity/contracts/equations/weighted-equation.clar
  clarity/contracts/equations/yield-token-equation.clar
  clarity/contracts/flash-loan-user-margin-usda-wbtc-59760.clar
  clarity/contracts/key-token/key-wbtc-59760-usda.clar
  clarity/contracts/key-token/key-wbtc-79760-usda.clar
  clarity/contracts/open-oracle.clar
  clarity/contracts/pool-token/fwp-wbtc-usda-50-50.clar
  clarity/contracts/pool-token/ytp-yield-wbtc-59760-wbtc.clar
  clarity/contracts/pool-token/ytp-yield-wbtc-79760-wbtc.clar
  clarity/contracts/pool/alex-reserve-pool.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/contracts/pool/fixed-weight-pool.clar
  clarity/contracts/pool/liquidity-bootstrapping-pool.clar
  clarity/contracts/pool/yield-token-pool.clar
  clarity/contracts/token/token-alex.clar
  clarity/contracts/token/token-usda.clar
  clarity/contracts/token/token-wbtc.clar
  clarity/contracts/traits/trait-ownable.clar
  clarity/contracts/yield-token/yield-wbtc-59760.clar
  clarity/contracts/yield-token/yield-wbtc-79760.clar
  clarity/deploy-util/README.md
  clarity/deploy-util/scripts/check.py
  clarity/deploy-util/scripts/deploy.py
  clarity/deploy-util/scripts/get-balance.py
  clarity/deploy-util/scripts/get-nonce.clar
  clarity/deploy-util/scripts/get-nonce.py
  clarity/deploy-util/scripts/initialize-account.py
  clarity/deploy-util/scripts/initialize-nonce.py
  clarity/tests/fixed-weight-pool_test.ts
  init-js-tool/deploy.js
  init-js-tool/index.js
  init-js-tool/package-lock.json
  init-js-tool/package.json
  init-js-tool/pools.js
Labels: dev

#232 Swaps scripts
  init-js-tool/deploy.js
  init-js-tool/flashloan.js
  init-js-tool/index.js
  init-js-tool/oracles.js
  init-js-tool/pools-crp.js
  init-js-tool/pools-fwp.js
  init-js-tool/pools-ytp.js
  init-js-tool/pools.js
  init-js-tool/utils.js
  init-js-tool/vault.js
Labels: dev

#234 Fix/crp/no add position post conversion
  clarity/Clarinet.toml
  clarity/contracts/equations/yield-token-equation.clar
  clarity/contracts/key-token/key-wbtc-59760-wbtc.clar
  clarity/contracts/multisig/multisig-crp-wbtc-59760-wbtc.clar
  clarity/contracts/pool/collateral-rebalancing-pool.clar
  clarity/tests/collateral-rebalancing-pool_test.ts
  clarity/tests/models/alex-tests-collateral-rebalancing-pool.ts
Labels: dev
